### ISSUE TITLE
Consider including a manifest task

### ISSUE THREAD

**Issue by gnarf** [gruntjs/grunt-init-jquery#5]
https://github.com/gnarf37/jquery-requestAnimationFrame/blob/8866ad1516b8414267148df2cbec544d09ea4314/grunt.js#L60-L81

**Comment by cowboy** [comment]
Corey, thanks for the issue. This is something I've actually given a lot of thought to.

jQuery plugins site metadata doesn't belong in `package.json`. You'll notice that while this init template does create a `package.json` file, that file doesn't contain any jQuery-specific information, and exists solely as a means for npm dependencies to be stored and for `npm install` to work.

It doesn't make sense to store project metadata in `package.json` if the project isn't going to be published to npm. There is actually an open issue isaacs/npm#914 to make name and version in `package.json` optional, because many projects that utilize npm are never published. They use npm modules solely as dev dependencies, and `package.json` solely as a place to store the list of dev dependencies. Like jQuery plugin projects that use Grunt and Grunt plugins.

You don't need to use `package.json` to store your metadata. That's a file for npm to consume. If you're doing npm things, use it. If not, you can safely ignore it. Eg. it's not like you put non-git stuff in your `.gitignore` file.

Now, the original location of the jQuery metadata doesn't need to be the jQuery manifest file. That manifest file could be generated from another data source. This could be really useful for programmatically generating a suite of jQuery plugins. For example, it makes sense for jQuery UI to store shared metadata in a separate file. Not `package.json` though, but a separate "master" jQuery metadata file. If I was going to go that route, I'd probably store the data in YAML and not JSON, because I prefer YAML as a metadata format for hand-editing.

That being said, the amount of jQuery plugin manifest file editing I've done has been extremely minimal. I haven't felt the need to build a manifest file yet, so I'm going to just leave the jQuery plugin metadata in its file, leave the npm stuff in `package.json`, and call it a day.

I advise you to do the same.

**Comment by cowboy** [comment]
PS. Update to Grunt 0.4!

**Comment by gnarf** [comment]
Either way, generating a manifest file that stays up to date with the npm package.json version using meta data from whatever config source (perhaps the grunt task itself) will save authors quite a bit of time.

I have found `grunt manifest` very useful.

**Comment by cowboy** [comment]
For jQuery plugins, you don't need to store any metadata other than your project's list of npm dev dependencies in the `package.json` file. Use a placeholder name and version in `package.json` like [this example](https://github.com/cowboy/jquery-tiny-pubsub/blob/master/package.json).
